### ISSUE TITLE
MoKredit 3D carousel banner - Homepage 

### ISSUE THREAD

**Issue by Saee1799** [ajency/bueno-finance-new#125]
1. Features that are being highlighted should be in chronological order. Right now its switching to any point randomly. 
![image](https://user-images.githubusercontent.com/96518669/158739716-311f55d6-0f91-4217-a8a5-a9aaec4fa286.png)

2. The phone screen is slightly out of the mockup frame. Could you shift the screenshot towards the right so the screen does not pop out of the mockup
![image](https://user-images.githubusercontent.com/96518669/158739902-360ccd39-94aa-4fac-9553-0541f1824104.png)

**Comment by EktaNaik** [comment]
@MamataNivajekar Please find my comments below and action accordingly.

1. Features are already being highlighted in chronological order, hence no need to fix. The order is as:
![image](https://user-images.githubusercontent.com/44566188/158741886-1faf3ef4-94c3-42b4-8284-e7f763fc02e1.png)

2. Please check and shift the screenshot towards the right slightly

**Comment by EktaNaik** [comment]
@Saee1799 The white space besides the phone frame is because of the width of the default white screen. See screenshot.
![image](https://user-images.githubusercontent.com/44566188/158751800-ad515720-bf71-42ed-9ed8-60ae1629a733.png)

Please reduce its width to make it same as that of the mobile frame so that it does not flow out of the mobile frame. See screenshot of slider with the white screen disabled.
![image](https://user-images.githubusercontent.com/44566188/158751960-4fe3d4b7-e456-4c11-9f83-09478783d4b1.png)

**Comment by Saee1799** [comment]
@EktaNaik 
I checked the default screen width, its correct. It just needs to be right aligned with the mockup screen. The problem is occurring because the default screen is center aligned with the mockup screen. The width of the default screen is 447px whereas the width of the mockup is 452 px. 
I'll add a video to explain what is happening below. 

https://user-images.githubusercontent.com/96518669/158753080-4308aefc-6674-4fbc-9361-0f4b4f62452f.mp4


![image](https://user-images.githubusercontent.com/96518669/158753649-d3ef3df2-a6c8-4929-bffb-c9879f65cb2e.png)
