### ISSUE TITLE
Home - Customer Testimonial: Color of quotation mark & text is incorrect

### ISSUE THREAD

**Issue by EktaNaik** [ajency/bueno-finance-new#74]
**Description**:

- Color of quotation mark of Customer Testimonial section is incorrect.
- Also, color of customer name and designation is incorrect. It should be #175B1E.
- Change it as per design.

**Screenshot**:
![image](https://user-images.githubusercontent.com/44566188/156766703-600086e5-63ea-4a63-8bf7-870132afb10c.png)

**Comment by ShivaniAjency** [comment]
Color of customer name and designation is incorrect. It should be #175B1E. --> Done


Description:

1. Color of the quotation mark of the Customer Testimonial section is incorrect. --> **The quotation marks are missing on the site** This has also been seen mac

2. The alignment of pagination is incorrect. This issue was seen in chrome and firefox (Windows). 

Screenshot:
Site:
![image](https://user-images.githubusercontent.com/75774252/157171050-e552e797-110e-4659-80b4-dbdc83962eb6.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/157171359-2ffe545c-5e20-4e99-9109-66f43cf60731.png)

**Comment by ShivaniAjency** [comment]
Mweb:
There is repetition and overlapping of quotation mark
![image](https://user-images.githubusercontent.com/75774252/157174077-f5f44c02-c4ef-415d-9a09-8698ddccb17f.png)

**Comment by ShivaniAjency** [comment]
Done
